TRUNCATE TABLE `PREFIX_connections`;
TRUNCATE TABLE `PREFIX_connections_page`;
TRUNCATE TABLE `PREFIX_connections_source`;
TRUNCATE TABLE `PREFIX_search_index`;
TRUNCATE TABLE `PREFIX_search_word`;
TRUNCATE TABLE `PREFIX_sekeyword`;
TRUNCATE TABLE `PREFIX_store`;